/* SPDX-License-Identifier: LicenseRef-Peakly-Free-Use-1.0 */
/* Peakly parser plugin TEMPLATE. Copy to src/parsers/<your-format-id>.js, then replace every "myformat" / TODO.
   Files whose name starts with "_" are NOT loaded by build.js or tests/run.js, so this template never registers.

   Header comment checklist (keep it in your copy):
   Peakly parser plugin "<id>": <one-line description of the instrument / software and export>.
     Format: <layout: header lines, delimiter, columns, units, binary offsets ...>
     Sniff: <what in the first 4 KB identifies it, and the score returned>
     Variants: <locales, versions, optional sections you handle (and ones you do not)>
     Format knowledge: <public spec / documentation / your own exported files; NEVER code from GPL/LGPL/AGPL/EPL readers>
     Sample: samples/data/<id>.<ext> (synthetic, CC0, generated by tools/make-samples.js) */
(function (PK) {
  'use strict';
  var P = PK.parsers;
  var H = P._h; // shared helpers, documented at the top of src/parsers/registry.js
  var baseName = H.baseName, splitLines = H.splitLines, kvMeta = H.kvMeta, deriveMeta = H.deriveMeta,
    mkTrace = H.mkTrace, tableToResult = H.tableToResult, fail = H.fail, okRes = H.okRes;
  var FORMAT = 'My instrument export'; // TODO: human-readable name (shown in the UI and in error messages)

  P.register({
    id: 'myformat',            // TODO: unique, lowercase, dash-separated; the same as the file name
    order: 500,                // optional: position in the supported-formats list and sniff tie-breaks (built-ins use 10-160)
    name: FORMAT,
    extensions: ['txt'],       // TODO: lowercase, no dot; a match adds weight to the sniff score (generic csv/txt only +0.05)
    binary: false,             // true -> parse() receives an ArrayBuffer and sniff() gets the head decoded as latin1
    description: 'TODO: one line for the Help > Supported formats list.',

    // head = first 4096 characters (text) or bytes-as-latin1 (binary); filename may be ''; info = { size, textLike, encoding }.
    // Return 0..1. Be specific: >= 0.8 only for a signature nobody else writes; 0 when unsure.
    sniff: function (head, filename, info) {
      return /^MyInstrument export v\d/m.test(head) ? 0.9 : 0; // TODO
    },

    // Return a ParseResult: okRes(format, traces, warnings) or fail(format, 'actionable message').
    // Throwing is fine too: the registry turns it into "Could not read this file as <name>: <message>".
    parse: function (text, opts) {
      opts = opts || {};
      var lines = splitLines(text), cut = -1;
      for (var i = 0; i < lines.length; i++) if (/^\[Data\]\s*$/.test(lines[i])) { cut = i; break; } // TODO
      if (cut < 0) return fail(FORMAT, 'No [Data] section found. Re-export with the raw data option enabled.');
      var meta = deriveMeta(kvMeta(lines.slice(0, cut)));
      // Easiest path for tabular data: let the shared reader find the table, units, and roles.
      return tableToResult(lines.slice(cut + 1).join('\n'), FORMAT, opts, { xUnit: 'min', yUnit: 'mAU' }, meta);
      // Or build traces yourself (x is converted to minutes, sorted, NaN pairs dropped):
      //   var tr = mkTrace(meta.sampleName || baseName(opts.filename), xs, ys, 'sec', 'mAU', meta);
      //   tr.peaks = H.normPeaks([{ start: 1.2, apex: 1.3, end: 1.5, label: 'X', area: 12.3 }], 'min', 'myformat'); // optional
      //   return okRes(FORMAT, [tr], warnings);
    }

    // JSON dialects: also implement sniffJSON(obj) -> 0..1 and parseJSON(obj, opts) so a file the generic JSON plugin
    // picked up is handed to you (see chromatopy.js / mocca2.js).
  });
})(typeof window !== 'undefined' ? (window.PK = window.PK || {}) : (globalThis.PK = globalThis.PK || {}));
